sudo: required
language: ruby
cache: bundler
rvm:
- 2.6.5
jobs:
  include:
  - stage: test
    name: rubocop
    script: bundle exec rubocop
  - stage: test
    name: rspec
    script: gem install bundler & bundle exec rspec