sudo: required
language: ruby
cache: bundler
rvm:
- 3.0.1
jobs:
  include:
  - stage: test
    name: Linters
    script: bundle exec rubocop && bundle exec erblint --lint-all
  - stage: test
    name: rspec
    script: gem install bundler & bundle exec rspec